name: Setup Job
description: "Sets up a job with the required versions of Python, Terraform, and all other dependencies."
inputs:
  python_version:
    description: Target major version of Python used.
    required: false
    default: 3.11
  terraform_version:
    description: Target version of Terraform to be used.
    required: false
    default: 1.2.2


runs:
  using: composite
  steps:
    - name: Install Python
      run: |
        sudo apt-get update
        sudo apt-get install python${{ inputs.python_version }} python3-pip -y
        echo "Installed Python $(python${{ inputs.python_version }} --version)"
      shell: bash

    - name: Install Terraform
      run: |
        mkdir .tmp
        curl -o .tmp/tf.zip https://releases.hashicorp.com/terraform/${{ inputs.terraform_version }}/terraform_${{ inputs.terraform_version }}_linux_amd64.zip
        cd .tmp
        unzip tf.zip
        sudo mv terraform /usr/local/bin/
        cd ..
        rm -rf .tmp
        echo "Installed version $(terraform -version) of Terraform"
      shell: bash
